//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Promotion
    {
        public int Promotion_Id { get; set; }
        public int Pass_Id { get; set; }
        public string Promo_Desc { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> Num_Classes { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMMM dd, yyyy}")]
        public DateTime Promo_End { get; set; }
    
        public virtual Class_Passes Class_Passes { get; set; }
    }
}
