//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Class_Log = new HashSet<Class_Log>();
        }
    
        public int Schedule_Id { get; set; }
        public int Teacher_Id { get; set; }
        public int Class_Id { get; set; }
        public int Room_Id { get; set; }
        public TimeSpan Start_Time { get; set; }
        public DateTime Class_Date { get; set; }
        public int Signed_Up { get; set; }
        public Nullable<int> Group_Id { get; set; }
        public string Schedule_Status { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_Log> Class_Log { get; set; }
        public virtual Room Room { get; set; }
        public virtual Yoga_User Yoga_User { get; set; }
    }
}
